spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vie?characterEncoding=utf8&serverTimezone=UTC&useUnicode=true
    username: root
    #    password: 525300
    #    password: g111519946
    password: abc13798111003